[Platform]: Downloads page schema
opentargets/ot-ui-apps pull request #233
Opened 2023-09-15 17:24 UTC by chinmehta

# [Platform]: Downloads page schema

## Using "serialisedSchema" from downloads file and showing in downloads table.

**Issue:** # [issue-2940](https://github.com/opentargets/issues/issues/2940)
**Deploy preview:** https://deploy-preview-233--ot-platform.netlify.app/downloads

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [x] Test A:  go to to downloads page and click on new column item in the table to see schema

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2023-09-17 22:33 UTC, LucaFumis approved these changes
Thanks @chinmehta - looks good

2023-09-17 23:56 UTC, carcruz requested changes

2023-09-17 23:56 UTC, carcruz commented on apps/platform/src/pages/DownloadsPage/DownloadsSchemaDrawer.jsx
Can you please add:
- Loading state on initial request with message "Loading downloads information" and circular loader component
- Overflow-y scroll style in the schema container to avoid scrolling in the drawer

2023-09-17 23:56 UTC, carcruz commented on apps/platform/src/pages/DownloadsPage/DownloadsSchemaDrawer.jsx
@d0choa can you please review the format output of the [schema](https://deploy-preview-233--ot-platform.netlify.app/downloads)?

2023-09-19 08:21 UTC, carcruz approved these changes

2023-09-19 08:22 UTC, merged