[Package]: migrate ClinvarStars component to TypeScript
opentargets/ot-ui-apps pull request #263
Opened 2023-09-27 20:39 UTC by raskolnikov-rodion

## Description

Migrate the ClinvarStars component to TypeScript.

## Type of change

- [X] TypeScript refactor

## How Has This Been Tested?

Applications were built locally. Component was manually inspected in the UI.

![image](https://github.com/opentargets/ot-ui-apps/assets/22417165/f379a56b-386d-4e38-9fa1-8fc3ad19d1ad)

## Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2023-09-27 20:45 UTC, raskolnikov-rodion commented
Hello @carcruz!

Can you help me with one question about this component? On line 30, it sets `starNum` to -1 at every iteration of the loop. If I'm not mistaken, this will result in displaying at most 1 star filled regardless of the value of the argument `num`. Is this intentional?

2023-09-28 22:21 UTC, carcruz commented
> Hello @carcruz!
> 
> Can you help me with one question about this component? At line 30, it sets `starNum` to -1 at every iteration of the loop. If I'm not mistaken, this will result in displaying at most 1 star filled regardless of the value of the argument `num`. Is this intentional?

Hello @raskolnikov-rodion yes, this is intentional

2023-10-10 10:15 UTC, carcruz requested changes

2023-10-10 10:15 UTC, carcruz commented on packages/ui/src/components/ClinvarStars.tsx
> +export default function ClinvarStars({ num, length = 4 }: ClinvarStarsProps) {
We don't use `export` in the Component declaration. Please roll back to `export default` after declaration.

2023-10-25 13:51 UTC, carcruz approved these changes

2023-10-25 13:51 UTC, merged