[Platform] Add metadata to variant page
opentargets/ot-ui-apps pull request #369
Opened 2024-05-08 14:50 UTC by gjmcn

## Description

Added profile to variants page with metadata.

**Issue:** https://github.com/opentargets/issues/issues/3299

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Load variant page with dev server (e.g. http://localhost:3000/variant/20_31257670_C_T).

## Checklist:

- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-13 14:15 UTC, chinmehta requested changes

2024-05-13 18:51 UTC, gjmcn commented on apps/platform/src/pages/VariantPage/Profile.tsx
> +import { ProfileHeader as BaseProfileHeader, Field } from "ui";
Pushed.

2024-05-13 18:51 UTC, gjmcn commented on apps/platform/src/pages/VariantPage/Profile.tsx
> +      <>
Pushed

2024-05-13 18:57 UTC, gjmcn commented on apps/platform/src/pages/VariantPage/Profile.tsx
> +          {`${metadata.chromosome}:${metadata.position}`}
Pushed.

2024-05-24 08:24 UTC, gjmcn commented
Replaced by PR #376

2024-05-24 08:24 UTC, closed without merging