gene prioritisation component tabs
opentargets/ot-ui-apps pull request #37
Opened 2022-07-26 16:22 UTC by chinmehta

[x] Made a separate section under study locus page for Genes Prioritisation Tabs instead of component.
[x] Gene Prioritisation Tabs section component take input for making separate gql call.
[x] Added Skeleton for loading state.
[x] Part of issue #: https://github.com/opentargets/issues/issues/2662

2022-07-26 17:35 UTC, carcruz requested changes

2022-07-26 17:35 UTC, carcruz commented on apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx
> +  },
Remove commented code

2022-07-26 17:35 UTC, carcruz commented on apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx
> +    ),
Fragment component

2022-07-26 17:35 UTC, carcruz commented on apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx
> +    <React.Fragment>
Fragment component

2022-07-26 17:35 UTC, carcruz commented on apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx
> +          <React.Fragment>
Fragment component

2022-07-27 08:27 UTC, chinmehta commented on apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx
> +  },
Done

2022-07-27 08:27 UTC, chinmehta commented on apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx
> +    ),
Done

2022-07-27 08:27 UTC, chinmehta commented on apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx
> +    <React.Fragment>
Done

2022-07-27 08:27 UTC, chinmehta commented on apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx
> +          <React.Fragment>
Done

2022-07-27 09:04 UTC, carcruz approved these changes

2022-07-27 09:50 UTC, merged