[Platform] Use React for state management in literature section
opentargets/ot-ui-apps pull request #416
Opened 2024-07-18 14:45 UTC by gjmcn

## Description

Use React instead of Recoil for state management in literature section.

**Issue:** [#3292](https://github.com/opentargets/issues/issues/3292)

## Type of change

## How Has This Been Tested?

Checked in dev.

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have made corresponding changes to the documentation

2024-07-18 16:48 UTC, carcruz requested changes
Please remove old highlighted folder/files of the PR to reflect the concise changes

2024-07-19 08:50 UTC, gjmcn commented
Is it best to leave them until we are sure no other tweaks for the state mgmt are needed? - all profile pages show only the new literature widget then the old for easy comparison. (Admittedly, it would have been better to leave the original folder name unchanged!)

2024-07-19 10:26 UTC, carcruz commented
> Is it best to leave them until we are sure no other tweaks for the state mgmt are needed? - all profile pages show only the new literature widget then the old for easy comparison. (Admittedly, it would have been better to leave the original folder name unchanged!)

No. We have tools as git, GitHub, GitHub spaces and our dev environments to compare and/or revert. It is important for better PRs reviews to be clear about the intended code added/removed

2024-07-19 12:57 UTC, gjmcn commented
OK, should be cleaner now.

2024-07-29 13:27 UTC, carcruz requested changes

2024-07-29 13:27 UTC, carcruz commented on packages/sections/src/common/Literature/Body.jsx
> +// };
Remove commented

2024-07-29 13:27 UTC, carcruz commented on packages/sections/src/common/Literature/LiteratureContext.tsx
> +  console.log(`LITERATURE REDUCER: ${action.type}`);
Remove log

2024-07-29 13:27 UTC, carcruz commented on packages/sections/src/common/Literature/LiteratureContext.tsx
> +const LiteratureContext = createContext(null as any);
Please use the LiteratureStateType

```jsx
const LiteratureContex = createContext<LiteratureStateType>(initial_state);
```

2024-07-29 13:27 UTC, carcruz commented on packages/sections/src/common/Literature/LiteratureContext.tsx
> +const LiteratureDispatchContext = createContext(null as any);
For typing the actions, you can use the same pattern of AotF FocusState https://github.com/opentargets/ot-ui-apps/blob/4e9fc2e5e25e2cccd32f338aad99d77be59b0f6a/apps/platform/src/components/AssociationsToolkit/context/AssociationsFocusContext.tsx#L18

2024-07-29 13:27 UTC, carcruz commented on packages/sections/src/common/Literature/LiteratureContext.tsx
> +  console.log(`DETAILS REDUCER: ${action.type}`);
remove log

2024-07-29 13:27 UTC, carcruz commented on packages/sections/src/common/Literature/LiteratureContext.tsx
> +  return useContext(DetailsDispatchContext);
👍 Like this approach. cc: @chinmehta

2024-07-29 13:27 UTC, carcruz commented on packages/sections/src/common/Literature/PublicationsList.tsx
> +        {/* <Box pt="1px"> */}
remove comment

2025-01-31 14:27 UTC, carcruz approved these changes

2025-01-31 14:27 UTC, merged